### ISSUE TITLE
app role should not need to copy the kubeconfig file

### ISSUE THREAD

**Issue by dhellmann** [redhat-cop/edge.microshift#33]
##### SUMMARY

The app role copies the localhost kubeconfig file into the root user's `.kube` directory, but that step is only needed if the user is going to run `oc` or `kubectl` on the local host. It would be better to move that step out to a separate role. We probably want a role to retrieve the correct kubeconfig file to access the API server remotely, too.

##### ISSUE TYPE
- Bug Report

I'm not sure this is really a "bug".

##### COMPONENT NAME

roles/app

https://github.com/ansible-collections/edge.microshift/blob/main/roles/app/tasks/main.yml#L37-L48

##### ANSIBLE VERSION

N/A

##### COLLECTION VERSION

N/A

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

N/A

##### ACTUAL RESULTS

```paste below

```

**Comment by DanielFroehlich** [comment]
actually, it would be better not to copy the kubeconfig file, but either create a symlink, or add and `export KUBECONFIG=/var/lib/microshift/resources/kubeadmin/kubeconfig` to `.profile`. Because there's a cert in that kubeconfig which might be re-generated, e.g. on hostname change, cert expiry etc.

**Comment by DanielFroehlich** [comment]
I just realised that this is about the app role. I agree that handling the kubeconfig does not belong to app deployment at all. 
So I am going to remove it their, and switch the rpm install to the .profile approach.
